### ISSUE TITLE
License for the template

### ISSUE THREAD

**Issue by l2dy** [jihchi/vitejs-template-react-rescript#6]
Could you add a public domain "license" like [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) to this repository? Simple template projects like this are likely not copyrightable, but explicitly putting it under the public domain is more reassuring.

**Comment by jihchi** [comment]
Thanks for the reminder.

I've added a license file in commit 818049d1eb4901d0ae5f4401f8cb3e7436477058.
