### ISSUE TITLE
How to use in-source: false

### ISSUE THREAD

**Issue by gavr123456789** [jihchi/vitejs-template-react-rescript#7]
Hello, Im newbe in rescript, this example is first time I run it.  
Thanks, it works great(every electron rescript example failed for me).  
But I don't want to have copies of every file in js format.  
After I changed the "in-source" setting: false and js started being generated inside lib I started getting a blank page, there are no errors.

**Comment by jihchi** [comment]
Please refer to the document of [`vite-plugin-rescript`](https://github.com/jihchi/vite-plugin-rescript#using-loader) (**Using Loader** section), you could setup a configuration to support `"in-source": false` setting.
